package ADO01;

import javax.swing.JOptionPane;

/**
 *
 * @author bruna.ssjodai
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ListaSimples lista = new ListaSimples();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupOpcoes = new javax.swing.ButtonGroup();
        tabPane = new javax.swing.JTabbedPane();
        panelOpcoes = new javax.swing.JPanel();
        radioInsereInicio = new javax.swing.JRadioButton();
        radioInsereFinal = new javax.swing.JRadioButton();
        radioPesquisa = new javax.swing.JRadioButton();
        radioImprime = new javax.swing.JRadioButton();
        radioRemoveUm = new javax.swing.JRadioButton();
        radioRemoveTodos = new javax.swing.JRadioButton();
        buttonOk = new javax.swing.JButton();
        lblOpcoes = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        lblModeloInicio = new javax.swing.JLabel();
        txtModeloInicio = new javax.swing.JTextField();
        lblMarcaInicio = new javax.swing.JLabel();
        txtMarcaInicio = new javax.swing.JTextField();
        lblAnoInicio = new javax.swing.JLabel();
        txtAnoInicio = new javax.swing.JTextField();
        buttonAddInicio = new javax.swing.JButton();
        panelFinal = new javax.swing.JPanel();
        lblModeloFinal = new javax.swing.JLabel();
        txtModeloFinal = new javax.swing.JTextField();
        lblMarcaFinal = new javax.swing.JLabel();
        txtAnoFinal = new javax.swing.JTextField();
        lblAnoFinal = new javax.swing.JLabel();
        txtMarcaFinal = new javax.swing.JTextField();
        buttonAddFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        panelOpcoes.setToolTipText("");

        groupOpcoes.add(radioInsereInicio);
        radioInsereInicio.setText("Inserir dados do carro no início da lista");

        groupOpcoes.add(radioInsereFinal);
        radioInsereFinal.setText("Inserir dados do carro no final da lista");

        groupOpcoes.add(radioPesquisa);
        radioPesquisa.setText("Pesquisar pelo modelo do carro");

        groupOpcoes.add(radioImprime);
        radioImprime.setText("Imprimir todos os elementos da lista");

        groupOpcoes.add(radioRemoveUm);
        radioRemoveUm.setText("Remover um elemento pelo modelo");

        groupOpcoes.add(radioRemoveTodos);
        radioRemoveTodos.setText("Remover todos os elementos da lista");

        buttonOk.setText("Pronto");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        lblOpcoes.setText("Escolha uma das opções:");

        javax.swing.GroupLayout panelOpcoesLayout = new javax.swing.GroupLayout(panelOpcoes);
        panelOpcoes.setLayout(panelOpcoesLayout);
        panelOpcoesLayout.setHorizontalGroup(
            panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcoesLayout.createSequentialGroup()
                .addGroup(panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioImprime)
                            .addComponent(radioRemoveUm)
                            .addComponent(radioInsereInicio)
                            .addComponent(radioInsereFinal)
                            .addComponent(radioPesquisa)
                            .addComponent(lblOpcoes)
                            .addComponent(radioRemoveTodos)))
                    .addGroup(panelOpcoesLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(buttonOk)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        panelOpcoesLayout.setVerticalGroup(
            panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcoesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblOpcoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioInsereInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioInsereFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioImprime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRemoveUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRemoveTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPane.addTab("Menu", panelOpcoes);

        lblModeloInicio.setText("Modelo");

        lblMarcaInicio.setText("Marca");

        lblAnoInicio.setText("Ano");

        buttonAddInicio.setText("Adicionar");
        buttonAddInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAddInicio)
                    .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInicioLayout.createSequentialGroup()
                            .addComponent(lblModeloInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtModeloInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelInicioLayout.createSequentialGroup()
                            .addComponent(lblMarcaInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMarcaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelInicioLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(lblAnoInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloInicio)
                    .addComponent(txtModeloInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaInicio)
                    .addComponent(txtMarcaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoInicio)
                    .addComponent(txtAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAddInicio)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        tabPane.addTab("Add Início", panelInicio);

        lblModeloFinal.setText("Modelo");

        lblMarcaFinal.setText("Marca");

        lblAnoFinal.setText("Ano");

        buttonAddFinal.setText("Adicionar");
        buttonAddFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAddFinal)
                    .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFinalLayout.createSequentialGroup()
                            .addComponent(lblModeloFinal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtModeloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelFinalLayout.createSequentialGroup()
                            .addComponent(lblMarcaFinal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMarcaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelFinalLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(lblAnoFinal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloFinal)
                    .addComponent(txtModeloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaFinal)
                    .addComponent(txtMarcaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoFinal)
                    .addComponent(txtAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAddFinal)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        tabPane.addTab("Add Final", panelFinal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        if (radioInsereInicio.isSelected()) {
            tabPane.setSelectedIndex(1);
            
            groupOpcoes.clearSelection();

        } else if (radioInsereFinal.isSelected()) {
            tabPane.setSelectedIndex(2);

            groupOpcoes.clearSelection();

        } else if (radioPesquisa.isSelected()) {
            String pesquisa = JOptionPane.showInputDialog("Digite o modelo p/ pesquisar");

            String result = lista.pesquisarNo(pesquisa);

            JOptionPane.showMessageDialog(this, result);
            
            groupOpcoes.clearSelection();

        } else if (radioImprime.isSelected()) {
            JOptionPane.showMessageDialog(this, lista.imprimirLista());

            groupOpcoes.clearSelection();

        } else if (radioRemoveUm.isSelected()) {
            String remove = JOptionPane.showInputDialog("Digite o modelo p/ remover");

            if (!remove.equals("") && lista.removerNo(remove)) {
                JOptionPane.showMessageDialog(this, "Removido com sucesso!");

                groupOpcoes.clearSelection();

            } else {
                JOptionPane.showMessageDialog(this, "Falha ao remover");
            }

        } else if (radioRemoveTodos.isSelected()) {
            if (lista.removerTudo()) {
                JOptionPane.showMessageDialog(this, "Todos os elementos foram removidos"
                        + " com sucesso!");

                groupOpcoes.clearSelection();

            } else {
                JOptionPane.showMessageDialog(rootPane, this,
                        "Falha ao remover", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma opção selecionada!");
        }
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonAddInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddInicioActionPerformed
        try {
            Carro c = new Carro();

            c.setModelo(txtModeloInicio.getText());
            c.setMarca(txtMarcaInicio.getText());
            c.setAno(Integer.parseInt(txtAnoInicio.getText()));

            lista.inserirPrimeiro(c);

            JOptionPane.showMessageDialog(this, "Adicionado com sucesso!");
            
            txtModeloInicio.setText("");
            txtMarcaInicio.setText("");
            txtAnoInicio.setText("");

            tabPane.setSelectedIndex(0);

        } catch (Exception e) {
            //Se ocorrer algum erro técnico, mostra-o no console,
            //mas esconde-o do usuário
            e.printStackTrace();

            //Exibe uma mensagem de erro genérica ao usuário
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Falha ao adicionar", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buttonAddInicioActionPerformed

    private void buttonAddFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddFinalActionPerformed
        try {
            Carro c = new Carro();

            c.setModelo(txtModeloFinal.getText());
            c.setMarca(txtMarcaFinal.getText());
            c.setAno(Integer.parseInt(txtAnoFinal.getText()));

            lista.inserirUltimo(c);

            JOptionPane.showMessageDialog(this, "Adicionado com sucesso!");
            
            txtModeloFinal.setText("");
            txtMarcaFinal.setText("");
            txtAnoFinal.setText("");

            tabPane.setSelectedIndex(0);

        } catch (Exception e) {
            e.printStackTrace();

            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Falha ao adicionar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonAddFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddFinal;
    private javax.swing.JButton buttonAddInicio;
    private javax.swing.JButton buttonOk;
    private javax.swing.ButtonGroup groupOpcoes;
    private javax.swing.JLabel lblAnoFinal;
    private javax.swing.JLabel lblAnoInicio;
    private javax.swing.JLabel lblMarcaFinal;
    private javax.swing.JLabel lblMarcaInicio;
    private javax.swing.JLabel lblModeloFinal;
    private javax.swing.JLabel lblModeloInicio;
    private javax.swing.JLabel lblOpcoes;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelOpcoes;
    private javax.swing.JRadioButton radioImprime;
    private javax.swing.JRadioButton radioInsereFinal;
    private javax.swing.JRadioButton radioInsereInicio;
    private javax.swing.JRadioButton radioPesquisa;
    private javax.swing.JRadioButton radioRemoveTodos;
    private javax.swing.JRadioButton radioRemoveUm;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTextField txtAnoFinal;
    private javax.swing.JTextField txtAnoInicio;
    private javax.swing.JTextField txtMarcaFinal;
    private javax.swing.JTextField txtMarcaInicio;
    private javax.swing.JTextField txtModeloFinal;
    private javax.swing.JTextField txtModeloInicio;
    // End of variables declaration//GEN-END:variables
}
