package ADO01;

import javax.swing.JOptionPane;

/**
 *
 * @author bruna.ssjodai
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupOpcoes = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelOpcoes = new javax.swing.JPanel();
        radioInsereInicio = new javax.swing.JRadioButton();
        radioInsereFinal = new javax.swing.JRadioButton();
        radioPesquisa = new javax.swing.JRadioButton();
        radioImprime = new javax.swing.JRadioButton();
        radioRemoveUm = new javax.swing.JRadioButton();
        radioRemoveTodos = new javax.swing.JRadioButton();
        buttonOk = new javax.swing.JButton();
        lblOpcoes = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        panelFinal = new javax.swing.JPanel();
        panelPesquisa = new javax.swing.JPanel();
        panelImprime = new javax.swing.JPanel();
        panelRemoveUm = new javax.swing.JPanel();
        panelRemoveTodos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        panelOpcoes.setToolTipText("");

        groupOpcoes.add(radioInsereInicio);
        radioInsereInicio.setText("Inserir dados do carro no início da lista");

        groupOpcoes.add(radioInsereFinal);
        radioInsereFinal.setText("Inserir dados do carro no final da lista");

        groupOpcoes.add(radioPesquisa);
        radioPesquisa.setText("Pesquisar pelo modelo do carro");

        groupOpcoes.add(radioImprime);
        radioImprime.setText("Imprimir todos os elementos da lista");

        groupOpcoes.add(radioRemoveUm);
        radioRemoveUm.setText("Remover um elemento pelo modelo");

        groupOpcoes.add(radioRemoveTodos);
        radioRemoveTodos.setText("Remover todos os elementos da lista");

        buttonOk.setText("Pronto");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        lblOpcoes.setText("Escolha uma das opções:");

        javax.swing.GroupLayout panelOpcoesLayout = new javax.swing.GroupLayout(panelOpcoes);
        panelOpcoes.setLayout(panelOpcoesLayout);
        panelOpcoesLayout.setHorizontalGroup(
            panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcoesLayout.createSequentialGroup()
                .addGroup(panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioImprime)
                            .addComponent(radioRemoveUm)
                            .addComponent(radioInsereInicio)
                            .addComponent(radioInsereFinal)
                            .addComponent(radioPesquisa)
                            .addComponent(lblOpcoes)
                            .addComponent(radioRemoveTodos)))
                    .addGroup(panelOpcoesLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(buttonOk)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        panelOpcoesLayout.setVerticalGroup(
            panelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcoesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblOpcoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioInsereInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioInsereFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioImprime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRemoveUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRemoveTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu", panelOpcoes);

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add Início", panelInicio);

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add Final", panelFinal);

        javax.swing.GroupLayout panelPesquisaLayout = new javax.swing.GroupLayout(panelPesquisa);
        panelPesquisa.setLayout(panelPesquisaLayout);
        panelPesquisaLayout.setHorizontalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelPesquisaLayout.setVerticalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pesquisa", panelPesquisa);

        javax.swing.GroupLayout panelImprimeLayout = new javax.swing.GroupLayout(panelImprime);
        panelImprime.setLayout(panelImprimeLayout);
        panelImprimeLayout.setHorizontalGroup(
            panelImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelImprimeLayout.setVerticalGroup(
            panelImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Imprime", panelImprime);

        javax.swing.GroupLayout panelRemoveUmLayout = new javax.swing.GroupLayout(panelRemoveUm);
        panelRemoveUm.setLayout(panelRemoveUmLayout);
        panelRemoveUmLayout.setHorizontalGroup(
            panelRemoveUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelRemoveUmLayout.setVerticalGroup(
            panelRemoveUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Del Um", panelRemoveUm);

        javax.swing.GroupLayout panelRemoveTodosLayout = new javax.swing.GroupLayout(panelRemoveTodos);
        panelRemoveTodos.setLayout(panelRemoveTodosLayout);
        panelRemoveTodosLayout.setHorizontalGroup(
            panelRemoveTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelRemoveTodosLayout.setVerticalGroup(
            panelRemoveTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Del Todos", panelRemoveTodos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        if (radioInsereInicio.isSelected()) {

        } else if (radioInsereInicio.isSelected()) {

        } else if (radioPesquisa.isSelected()) {

        } else if (radioImprime.isSelected()) {

        } else if (radioRemoveUm.isSelected()) {

        } else if (radioRemoveTodos.isSelected()) {

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma opção selecionada!");
        }
    }//GEN-LAST:event_buttonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOk;
    private javax.swing.ButtonGroup groupOpcoes;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblOpcoes;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelImprime;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelOpcoes;
    private javax.swing.JPanel panelPesquisa;
    private javax.swing.JPanel panelRemoveTodos;
    private javax.swing.JPanel panelRemoveUm;
    private javax.swing.JRadioButton radioImprime;
    private javax.swing.JRadioButton radioInsereFinal;
    private javax.swing.JRadioButton radioInsereInicio;
    private javax.swing.JRadioButton radioPesquisa;
    private javax.swing.JRadioButton radioRemoveTodos;
    private javax.swing.JRadioButton radioRemoveUm;
    // End of variables declaration//GEN-END:variables
}
